# Generated by Django 4.2.23 on 2025-07-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionrecord',
            old_name='uploaded_at',
            new_name='timestamp',
        ),
    ]
