services:
  - type: web
    name: img-pred-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn img_pred.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: img_pred.settings
      - key: PYTHON_VERSION
        value: 3.10